### ISSUE TITLE
Consider making the switch for TfsCheckout default to false?

### ISSUE THREAD

**Issue by NigelDyson** [JoelHT-Landmark/NuGet-PackageNPublish#22]
Assumes that default audience are TFS users whereas Git users don't need to checkout in order for their build system to make version number changes.

**Comment by JoelHT-Landmark** [comment]
Fixed in the ISSUE-22 branch, but that's defunct..

So fixed (again) in [Commit c44b6b585a4c81a1ebef0c3fb3464ce5c20ffd40](https://github.com/JoelHT-Landmark/NuGet-PackageNPublish/commit/c44b6b585a4c81a1ebef0c3fb3464ce5c20ffd40)
